server:
  port: 8888

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/counter_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  kafka:
    consumer:
      group-id: app.1

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

  application.name: router
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: hello-service
          uri: lb://hello-service
          predicates:
            Path=/hello-service/**
          filters:
            - StripPrefix=1
        - id: bye-service
          uri: lb://bye-service
          predicates:
            Path=/bye-service/**
          filters:
            - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka